export enum ItemID {
    Lumber = 'Lumber',
    WoodPlank = 'WoodPlank',
    IronOre = 'IronOre',
    IronIngot = 'IronIngot',

    // Weapons
    IronSword = 'IronSword',
    IronSpear = 'IronSpear',
    WoodBow = 'WoodBow',
    ReinforcedWoodBow = 'ReinforcedWoodBow',
    WoodStaff = 'WoodStaff',
    IronDagger = 'IronDagger',

    // Armors
    IronShield = 'IronShield',
    IronHelmet = 'IronHelmet',
    IronPlate = 'IronPlate',
    IronMail = 'IronMail',
    IronGauntlet = 'IronGauntlet',
    IronPants = 'IronPants',
    IronBoots = 'IronBoots',
    ReinforcedWoodShield = 'ReinforcedWoodShield',
    LeatherHelmet = 'LeatherHelmet',
    LeatherChest = 'LeatherChest',
    LeatherPants = 'LeatherPants',
    LeatherBoots = 'LeatherBoots',
    LeatherGlove = 'LeatherGlove',
    WoodShield = 'WoodShield',

    // Herbs
    Greycap = 'Greycap',
    Stonemoss = 'Stonemoss',
    Thistlewort = 'Thistlewort',
    Hollowreed = 'Hollowreed',
    Bloodroot = 'Bloodroot',
    Manabloom = 'Manabloom',
    Sunleaf = 'Sunleaf',
    Oxroot = 'Oxroot',
    Bitterleaf = 'Bitterleaf',
    Ashcap = 'Ashcap',
    Coldmint = 'Coldmint',
    Sourberry = 'Sourberry',
    Copperfern = 'Copperfern',
    Duskbloom = 'Duskbloom',
    Gallnut = 'Gallnut',
    Mirebloom = 'Mirebloom',
    Witchhazel = 'Witchhazel',
    IronbarkMoss = 'IronbarkMoss',
    Bloodcap = 'Bloodcap',
    Foxglove = 'Foxglove',
    Moonwort = 'Moonwort',
    Nightshade = 'Nightshade',
    Emberfruit = 'Emberfruit',
    Amberseed = 'Amberseed',
    Frostcap = 'Frostcap',
    Ghostcap = 'Ghostcap',
    Glowspore = 'Glowspore',
    Cryptbloom = 'Cryptbloom',
    Starbloom = 'Starbloom',
    Silverleaf = 'Silverleaf',
    Heartsap = 'Heartsap',
    Emberheart = 'Emberheart',
    Kingsroot = 'Kingsroot',

    // Potions
    HealthPotion = 'HealthPotion',
    ManaPotion = 'ManaPotion',
}
